name: Deploy Frontend to GCP VM

on:
  push:
    branches: [ main ]  # 啟用自動觸發
  workflow_dispatch:    # 保留手動觸發選項

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    - name: Upload Playwright report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: echoedinvoker/lt-rank-frontend:latest
        build-args: |
          VITE_API_URL=/api
          VITE_USE_MOCK=false
          VITE_WEB_URL=https://ltrust.tw

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 34.81.184.55 >> ~/.ssh/known_hosts
    
    # - name: Test SSH Connection
    #   run: |
    #     ssh -i ~/.ssh/id_rsa ltrust_cheng@34.81.184.55 'echo "SSH connection successful!"'

    - name: Deploy on GCP VM
      run: |
        ssh -i ~/.ssh/id_rsa ltrust_cheng@34.81.184.55 << 'EOF'
          cd /home/ubuntu/lt-rank-web/
          sudo docker compose pull frontend
          sudo docker compose up -d frontend
          
          echo "Deployment completed!"
        EOF
