name: Deploy Frontend to GCP VM (Test)

on:
  workflow_dispatch:  # 只允許手動觸發
  # push:
  #   branches: [ main ]  # 先註解掉自動觸發

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: echoedinvoker/lt-rank-frontend:latest
        build-args: |
          VITE_API_URL=/api
          VITE_USE_MOCK=false
          VITE_WEB_URL=https://ltrust.tw
